baseurl = "https://ataylor.io/"
languageCode = "en-us"
title = "Aaron Taylor"
description = "My personal site"
disqusShortname = "kujengatech"
googleAnalytics = "UA-56787812-1"
copyright = "Â© Aaron Taylor 2015-{year}"
publishDir = "app/public"
relativeURLs = true

# allow HTML to be used in markdown files
[markup.goldmark.renderer]
  unsafe = true

[params]
	twitter = "https://twitter.com/ataylor0123"
	github = "https://github.com/kujenga"
	linkedin = "https://linkedin.com/in/ataylor0123"
	instagram = "https://instagram.com/ataylor0123/"
	angellist = "https://angel.co/ataylor0123"
	keybase = "https://keybase.io/ataylor"

# docs: https://gohugo.io/templates/menu-templates/
[menu]
  [[menu.nav]]
    identifier = "blog"
    name = "This is the blog section"
    title = "Blog"
    url = "/blog/"
    weight = -110
  [[menu.nav]]
    identifier = "about"
    name = "This the about section"
    title = "About"
    url = "/about/"
    weight = -100
